# Generated by Django 6.0.7 on 2026-07-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('stocks', models.IntegerField()),
                ('vitamin_e', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('glucosamine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crude_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('cups', models.IntegerField()),
                ('mix_with', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_guidelines', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('body', models.TextField()),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.product')),
            ],
        ),
    ]
