# Generated by Django 6.0.7 on 2026-08-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
